stages:
  - init
  - build
  - test

# Speed up parallel jobs of build stage be pre downloading image.
download:image:
  stage: init
  script:
    - docker pull datacore/ubuntu-crosscompile

build:linux:i686:
  stage: build
  image: datacore/ubuntu-crosscompile
  script:
    - cmake -E env CMAKE_C_FLAGS="-m32" cmake .
    - make all

build:linux:x86_64:
  stage: build
  image: datacore/ubuntu-crosscompile
  script:
    - cmake .
    - make all

build:windows:i686:
  stage: build
  image: datacore/ubuntu-crosscompile
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -y && apt-get install -y file
  script:
    - cmake -E env CMAKE_C_FLAGS="-m32" cmake .
    - CC=i686-w64-mingw32-gcc make all
    - file libunqlite.a


build:windows:x86_64:
  stage: build
  image: datacore/ubuntu-crosscompile
  script:
    - cmake .
    - CC=x86_64-w64-mingw32-gcc make all
